### ISSUE TITLE
Dov est un gros branleur

### ISSUE THREAD

**Issue by Seowlfh** [Renaud-Dov/Hermes#4]
Dans la partie "What is Hermes", la ligne "help me create the description of my program." est en train de pure chill. Elle n'a rien à faire là. Elle devrait partir. Rapidement. Cette ligne fait honte au projet. Elle ne renvoit pas une image de l'école et de l'équipe de développement convenable. aogooggugoogug

Dov t'es un branleur.

![image](https://github.com/Renaud-Dov/Hermes/assets/75431647/060f80ed-f480-4275-b2b7-78e8934fa3d9)

**Comment by Renaud-Dov** [comment]
🙂

**Comment by Seowlfh** [comment]
Close l'issue batard
